"""Criar tabela metrics k8

Revision ID: d651fbe350ec
Revises: d5e3f2a7c7df
Create Date: 2025-04-10 02:11:33.735522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd651fbe350ec'
down_revision: Union[str, None] = 'd5e3f2a7c7df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kubernetes_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('cluster_name', sa.String(), nullable=True),
    sa.Column('namespace', sa.String(), nullable=True),
    sa.Column('pod_name', sa.String(), nullable=True),
    sa.Column('container_name', sa.String(), nullable=True),
    sa.Column('metric_type', sa.String(), nullable=True),
    sa.Column('metric_name', sa.String(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('metadata', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kubernetes_metrics_cluster_name'), 'kubernetes_metrics', ['cluster_name'], unique=False)
    op.create_index(op.f('ix_kubernetes_metrics_metric_name'), 'kubernetes_metrics', ['metric_name'], unique=False)
    op.create_index(op.f('ix_kubernetes_metrics_metric_type'), 'kubernetes_metrics', ['metric_type'], unique=False)
    op.create_index(op.f('ix_kubernetes_metrics_namespace'), 'kubernetes_metrics', ['namespace'], unique=False)
    op.create_index(op.f('ix_kubernetes_metrics_pod_name'), 'kubernetes_metrics', ['pod_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kubernetes_metrics_pod_name'), table_name='kubernetes_metrics')
    op.drop_index(op.f('ix_kubernetes_metrics_namespace'), table_name='kubernetes_metrics')
    op.drop_index(op.f('ix_kubernetes_metrics_metric_type'), table_name='kubernetes_metrics')
    op.drop_index(op.f('ix_kubernetes_metrics_metric_name'), table_name='kubernetes_metrics')
    op.drop_index(op.f('ix_kubernetes_metrics_cluster_name'), table_name='kubernetes_metrics')
    op.drop_table('kubernetes_metrics')
    # ### end Alembic commands ###
